/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EfWUtqlx4dM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function NumericInput({ value, onChange, label, min, max, step }: { value: number; onChange: (value: number) => void; label: string; min?: number; max?: number; step?: number }) {
  return (
    <div className="flex w-full max-w-sm items-center space-x-2">
      <Label htmlFor="quantity">Quantity</Label>
      <Input type="number" id="quantity" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} />
    </div>
  )
}
