import { mapToUpsertPropertyListingInput } from './upsert-latest-property-news-listings';
import { PropertyListing_PropertyNews } from '@/repository/property-listings/property-news/types';

describe('mapToUpsertPropertyListingInput', () => {
  it('should map single PropertyListing_PropertyNews to UpsertPropertyListingInput', () => {
    const result = mapToUpsertPropertyListingInput(data[0] as any);
    console.log(result);
    // expect(result).toEqual(expectedResult);
  });

  it('should map multiple PropertyListing_PropertyNews to UpsertPropertyListingInput', () => {
    const result = data.map(mapToUpsertPropertyListingInput as any);
    console.log(result);
    // expect(result).toEqual(expectedResult);
  });
});

const data = [
  {
    id: 'OEW704221',
    propertyUrl: '/property-for-sale/dunnamona-road-omagh-bt78-1st/property/OEW704221/',
    address: {
      line1: 'Dunnamona Road',
      line2: '110M Ne Of 83 Dunnamona Road',
      town: 'Omagh',
      county: 'Tyrone',
      postcode: 'BT781ST',
    },
    leadImage: {
      name: '18483284.jpg',
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/OEW704221/photo/image/326ffbd8-3f99-461d-a003-d333a312307d/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/OEW704221/photo/image/326ffbd8-3f99-461d-a003-d333a312307d/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/OEW704221/photo/image/326ffbd8-3f99-461d-a003-d333a312307d/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/OEW704221/photo/image/326ffbd8-3f99-461d-a003-d333a312307d/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 5,
    price: 30000,
    currency: 'GBP',
    priceText: 'Offers Around',
    status: 'For Sale',
    bedrooms: 0,
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Site',
    propertyTypeLabel: 'Building Site (with FPP)',
    isNew: false,
    epcRatingCurrent: 0,
    epcRatingPotential: 0,
    agents: [
      {
        id: 12479,
        logo: {
          name: 'Outstanding Estate Agents',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/12479/logo/image/b89e04758347769429463d62d8212877/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/12479/logo/image/b89e04758347769429463d62d8212877/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/12479/logo/image/b89e04758347769429463d62d8212877/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/12479/logo/image/b89e04758347769429463d62d8212877/600x500.png',
            },
          ],
        },
        name: 'Outstanding Estate Agents',
        phoneNumber: '028 8224 8220',
        featured: false,
        companyInfo:
          "Our agents are dedicated to ensuring you receive the best possible price for your property and work around the clock to achieve this. We deal with all prospective buyers in a professional and friendly manner and keep you informed of all developments and offers, and offer expert advice in how best to respond.\r\n\r\nWe firmly believe that an honest appraisal is more important than over-valuing the property, we find that our no-nonsense approach gives your property a better chance of selling from day one!\r\n\r\nWhen a sale has been agreed we forward a Sale Agreed Notification to the instructed Solicitors. We then proceed to work closely with said Solicitors to ensure a smooth transaction for all.\r\n\r\nWHAT TO EXPECT WHEN YOU LIST WITH US\r\nFree of charge valuation service\r\nOur agents will visit your property on a day and time convenient to you to take measurements and photographs of your property\r\nA detailed listing of your property on our website and Propertynews.com for maximum exposure\r\nA professionally designed brochure, listing your property's key details available in our office and online\r\nFor Sale Sign (Optional) We find this to be a very useful tool in attracting potential buyers\r\nEvening and Weekend Viewings available on request. Our experienced agents work around the clock to arrange and accompany viewings at a time that suits both Vendors and purchasers\r\nFull disclosure of all details regarding viewings, offers and negotiations for all parties involved (Details retained for future reference & available on request)\r\nCompetitively priced EPC (Energy Performance Certificate)***\r\nContact Us about Selling your property\r\nRENTING A PROPERTY\r\nWith our rental management service we take the headache out of owning a rental property. During a tenancy we act swiftly to deal with any and all problems and repairs as they arise.\r\n\r\nWe also offer a one off 'find a tenant' service for more hands-on landlords.\r\n\r\nOUR RENTAL PACKAGE\r\nFull listing service at a time that suits you(Including Photographs & measurements)\r\nAdvertise your property on our website and Propertynews.com\r\nAccompanying all potential Tenants viewing the property\r\nCheck all references\r\nDraft Tenancy Agreement\r\nArrange payment of rent\r\n*** It is now legislation for all properties (residential and commercial) whether it is for sale or for rent to have an EPC. For more information visit: www.dfpni.gov.uk\r\n\r\nContact Us about Renting your property\r\nENERGY PERFORMANCE CERTIFICATES\r\nEnergy Performance Certificates (EPCs) are needed whenever a property is:\r\n\r\nBuilt\r\nSold\r\nRented\r\nYou must order an EPC for potential buyers and tenants before you market your property to sell or rent.\r\n\r\nAn EPC contains:\r\n\r\nInformation about a property's energy use and typical energy costs\r\nRecommendations about how to reduce energy use and save money\r\nAn EPC gives a property an energy efficiency rating from A (most efficient) to G (least efficient) and it is valid for 10 years.",
        address: {
          line1: '78 Market Street',
          town: 'Omagh',
          county: 'Co. Tyrone',
          postcode: 'BT79 0AA',
        },
        type: 'Estate Agent',
        chatEnabled: true,
        url: 'http://www.outstandingestateagents.com/',
      },
    ],
    location: 'gcdy0rr4p8',
    sector: ['Residential'],
  },
  {
    id: 'CSE9765',
    propertyUrl: '/property-for-sale/32-glencoppagh-road-plumbridge-bt79-8aw/property/CSE9765/',
    address: {
      line1: '@ 32 Glencoppagh Road',
      line2: 'Plumbridge',
      town: 'Plumbridge',
      county: 'Tyrone',
      postcode: 'BT798AW',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/CSE9765/photo/image/414b68f5-c8c4-4e12-8be3-3215452eb1e1/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/CSE9765/photo/image/414b68f5-c8c4-4e12-8be3-3215452eb1e1/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/CSE9765/photo/image/414b68f5-c8c4-4e12-8be3-3215452eb1e1/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/CSE9765/photo/image/414b68f5-c8c4-4e12-8be3-3215452eb1e1/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 5,
    price: 19950,
    currency: 'GBP',
    priceText: 'Fixed Price',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Land (Single Dwelling)',
    isNew: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 1445,
        logo: {
          name: 'Corry & Stewart Estate Agents',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/1445/logo/image/b265ce60fe4c5384e622b09eb829b8df/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/1445/logo/image/b265ce60fe4c5384e622b09eb829b8df/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/1445/logo/image/b265ce60fe4c5384e622b09eb829b8df/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/1445/logo/image/b265ce60fe4c5384e622b09eb829b8df/600x500.png',
            },
          ],
        },
        name: 'Corry & Stewart Estate Agents',
        phoneNumber: '028 8225 0500',
        featured: false,
        companyInfo:
          'The Corry & Stewart Group was established by Mr Noel Stewart and Mr Aidan Corry in 1998 and was based in Omagh.\r\n\r\nThis successful partnership ended mutually on the 1st January 2000 and Mr Corry went on to pursue a successful business in Financial Services & Retail. Noel Stewart retained the Corry & Stewart brand and built an excellent reputation for personal service, presentation and above all professionalism and honesty. Corry & Stewart are now widely recognised as a Dynamic Residential and Commercial Sales Specialist in the Omagh area.\r\n\r\nCorry & Stewart offer the following services to their customers:\r\n-\tResidential sales and lettings\r\n-\tCommercial sales and lettings\r\n-\tNew developments\r\n-\tLand/site sales\r\n',
        address: {
          line1: '36a High Street',
          town: 'Omagh',
          county: 'Co. Tyrone',
          postcode: 'BT78 1BP',
        },
        type: 'Estate Agent',
        chatEnabled: true,
        url: 'http://www.corryandstewart.com',
      },
    ],
    location: 'gcdzdv1nxf',
    locationDescription:
      'From Omagh, Travel out the Gortin Road into Plumbridge. Travel over Bridge in Plumbridge, Turn Left and the First Right after the Hair Dressers Shop onto Lisnaragh Road heading for Dunamanagh. Travel approximately &#x00bd; mile past the Secondary School and Take the 2nd Left called Glencoppagh Road. Travel approximately &#x00bd; mile.\nSee Corry & Stewart For Sale Sign on the Left Hand Side.',
    sector: ['Residential'],
  },
  {
    id: 'WPO500',
    propertyUrl: '/property-for-sale/32-lacky-road-enniskillen-bt92-7nq/property/WPO500/',
    address: {
      line1: '32 Lacky Road',
      line2: 'Roslea',
      town: 'Enniskillen',
      postcode: 'BT927NQ',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/WPO500/photo/image/c634df19-b8f5-4fa7-8a20-984afd055c90/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/WPO500/photo/image/c634df19-b8f5-4fa7-8a20-984afd055c90/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/WPO500/photo/image/c634df19-b8f5-4fa7-8a20-984afd055c90/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/WPO500/photo/image/c634df19-b8f5-4fa7-8a20-984afd055c90/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 11,
    price: 19950,
    currency: 'GBP',
    priceText: 'Guide Price',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 1,
    receptionRooms: 1,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Land',
    isNew: false,
    enhanced: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 12849,
        logo: {
          name: 'Watters Property Sales',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/12849/logo/image/090962d4-d79d-4727-8ddf-b5b14a26ef82/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/12849/logo/image/090962d4-d79d-4727-8ddf-b5b14a26ef82/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/12849/logo/image/090962d4-d79d-4727-8ddf-b5b14a26ef82/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/12849/logo/image/090962d4-d79d-4727-8ddf-b5b14a26ef82/600x500.png',
            },
          ],
        },
        name: 'Watters Property Sales',
        phoneNumber: '028 6602 2200',
        featured: true,
        address: {
          line1: 'UNIT 55 Enniskillen Business Centre',
          line2: '21 Lackaghboy Road',
          town: 'Enniskillen',
          county: 'Co. Fermanagh',
          postcode: 'BT74 4RL',
        },
        type: 'Estate Agent',
        chatEnabled: false,
        url: 'http://www.watterspropertysales.co.uk',
      },
    ],
    location: 'gcdu6zftw3',
    sector: ['Residential'],
  },
  {
    id: 'INS1042474',
    propertyUrl: '/property-for-sale/32-lacky-road-roslea-bt92-7nq/property/INS1042474/',
    address: {
      line1: '32 Lacky Road',
      line2: 'Drumswords',
      town: 'Roslea',
      county: 'Fermanagh',
      postcode: 'BT927NQ',
    },
    leadImage: {
      name: 'ajsfiajofjasjf.jpg',
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/INS1042474/photo/image/7e02d8a1-511a-46c3-b902-780a2c19f1ee/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/INS1042474/photo/image/7e02d8a1-511a-46c3-b902-780a2c19f1ee/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/INS1042474/photo/image/7e02d8a1-511a-46c3-b902-780a2c19f1ee/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/INS1042474/photo/image/7e02d8a1-511a-46c3-b902-780a2c19f1ee/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 12,
    price: 19950,
    currency: 'GBP',
    priceText: 'Offers Over',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Site',
    propertyTypeLabel: 'Site with FPP',
    isNew: false,
    enhanced: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 12840,
        logo: {
          name: 'Iamsold NI',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/12840/logo/image/f6d52fa4-044d-4ed0-9a0a-126fb26b5695/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/12840/logo/image/f6d52fa4-044d-4ed0-9a0a-126fb26b5695/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/12840/logo/image/f6d52fa4-044d-4ed0-9a0a-126fb26b5695/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/12840/logo/image/f6d52fa4-044d-4ed0-9a0a-126fb26b5695/600x500.png',
            },
          ],
        },
        name: 'Iamsold NI',
        phoneNumber: '028 9560 8380',
        featured: false,
        address: {
          line1: 'Scottish Provident Building',
          town: 'Belfast',
          county: 'Co. Antrim',
          postcode: 'BT1 6JH',
        },
        type: 'Estate Agent',
        chatEnabled: false,
        url: 'http://www.iamsoldni.com',
      },
    ],
    location: 'gcdu6zfq31',
    sector: ['Residential'],
  },
  {
    id: 'OBO794079',
    propertyUrl: '/property-for-sale/dunnamona-road-omagh-bt78-1st/property/OBO794079/',
    address: {
      buildingName: '10M Ne Of 83',
      line1: 'Dunnamona Road',
      town: 'Omagh',
      county: 'Tyrone',
      postcode: 'BT781ST',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/OBO794079/photo/image/96775dc1-1a72-4216-94cb-9c1806c53d0a/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/OBO794079/photo/image/96775dc1-1a72-4216-94cb-9c1806c53d0a/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/OBO794079/photo/image/96775dc1-1a72-4216-94cb-9c1806c53d0a/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/OBO794079/photo/image/96775dc1-1a72-4216-94cb-9c1806c53d0a/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 6,
    price: 29950,
    currency: 'GBP',
    priceText: 'Asking Price',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Building Site (with FPP)',
    isNew: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 2445,
        logo: {
          name: "O'Kane Bros",
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/2445/logo/image/9ed9328611fe3f45b3cce8ffe386ee97/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/2445/logo/image/9ed9328611fe3f45b3cce8ffe386ee97/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/2445/logo/image/9ed9328611fe3f45b3cce8ffe386ee97/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/2445/logo/image/9ed9328611fe3f45b3cce8ffe386ee97/600x500.png',
            },
          ],
        },
        name: "O'Kane Bros",
        phoneNumber: '028 8224 7575',
        featured: true,
        companyInfo:
          "O’Kane Bros Ltd is a chartered surveyor and estate agents based in Omagh, County Tyrone. O'Kane Bros Ltd Chartered Surveyors and Estate Agents was established 40 years ago by Peter O'Kane Snr. \r\n\r\nAs a family business, O'Kane Bros has grown from strength to strength over the past 4 decades and are now one of the most established property firms in Omagh and West of the Bann.\r\n\r\nPeter O'Kane Jnr is a qualified member of the Royal Institute of Chartered Surveyors (RICS) and the second generation of the O'Kane family to run the company. \r\n\r\nPeter is dedicated to maintaining the company reputation on honesty and integrity which has been built up over the 4 decades. The combined experience and varied specialisms within the company allow O’Kane Bros to provide a quality service in all aspects of the property market from valuations and auctions to residential/commercial sales and lettings.\r\n",
        address: {
          line1: '27 Market Street',
          town: 'Omagh',
          county: 'Co. Tyrone',
          postcode: 'BT78 1EE',
        },
        type: 'Estate Agent',
        chatEnabled: true,
        url: 'http://www.okanebrothers.co.uk',
      },
    ],
    location: 'gcdy237sxw',
    sector: ['Residential'],
  },
  {
    id: 'VEB82158-1-18543637',
    propertyUrl: '/property-for-sale/derrycrow-road-craigavon-bt66-6pt/property/VEB82158-1-18543637/',
    address: {
      buildingName: 'Land Adjacent To 11',
      line1: 'Derrycrow Road',
      town: 'Craigavon',
      county: 'Armagh',
      postcode: 'BT666PT',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/VEB82158-1-18543637/photo/image/e6e403bb-5a6f-41d2-b3c6-efd0560ac37a/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/VEB82158-1-18543637/photo/image/e6e403bb-5a6f-41d2-b3c6-efd0560ac37a/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/VEB82158-1-18543637/photo/image/e6e403bb-5a6f-41d2-b3c6-efd0560ac37a/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/VEB82158-1-18543637/photo/image/e6e403bb-5a6f-41d2-b3c6-efd0560ac37a/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 1,
    price: 25000,
    currency: 'GBP',
    priceText: 'Offers Over',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Land',
    isNew: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 12792,
        logo: {
          name: 'Marc Fegan - Bespoke Estate Agent',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/12792/logo/image/0497a5a3-ad62-4011-99e4-ace25ba80749/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/12792/logo/image/0497a5a3-ad62-4011-99e4-ace25ba80749/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/12792/logo/image/0497a5a3-ad62-4011-99e4-ace25ba80749/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/12792/logo/image/0497a5a3-ad62-4011-99e4-ace25ba80749/600x500.png',
            },
          ],
        },
        name: 'Marc Fegan - Bespoke Estate Agent',
        phoneNumber: '028 3889 4608',
        featured: false,
        companyInfo:
          'Marc Fegan has over 15 years experience across sales and lettings and in January 2020 he decided that enough was enough.\r\n\r\nHaving been employed with several different estate agents in a wide variety of roles Marc decided that there was a better way to do estate agency. He believed in a more personal experience, one where a trust and friendship is built with his clients not simply a business relationship! Hence the name Marc Fegan - Bespoke Estate Agent',
        address: {
          line1: '4 William Street',
          town: 'Lurgan',
          county: 'Co. Armagh',
          postcode: 'BT66 6JA',
        },
        type: 'Estate Agent',
        chatEnabled: true,
        url: 'https://www.marcfegan.co.uk/',
      },
    ],
    location: 'gceqhk4tvc',
    sector: ['Residential'],
  },
  {
    id: 'VEB82664-3-528251123',
    propertyUrl: '/property-for-sale/demesne-hollow-downpatrick-bt30-6wf/property/VEB82664-3-528251123/',
    address: {
      buildingName: 'Site 2 Adj To 5',
      line1: 'Demesne Hollow',
      town: 'Downpatrick',
      postcode: 'BT306WF',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/VEB82664-3-528251123/photo/image/d5798ba9-e1b6-4921-ab6e-ec0ff82ed609/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/VEB82664-3-528251123/photo/image/d5798ba9-e1b6-4921-ab6e-ec0ff82ed609/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/VEB82664-3-528251123/photo/image/d5798ba9-e1b6-4921-ab6e-ec0ff82ed609/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/VEB82664-3-528251123/photo/image/d5798ba9-e1b6-4921-ab6e-ec0ff82ed609/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 5,
    price: 25000,
    currency: 'GBP',
    priceText: 'Offers in the region of',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Plot',
    isNew: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 7920,
        logo: {
          name: 'Quinn Estate Agents (Downpatrick)',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/7920/logo/image/255ea887b8bca36797426dfb35a809cc/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/7920/logo/image/255ea887b8bca36797426dfb35a809cc/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/7920/logo/image/255ea887b8bca36797426dfb35a809cc/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/7920/logo/image/255ea887b8bca36797426dfb35a809cc/600x500.png',
            },
          ],
        },
        name: 'Quinn Estate Agents (Downpatrick)',
        phoneNumber: '028 4461 2100',
        featured: false,
        address: {
          line1: '49-51 Market Street',
          town: 'Downpatrick',
          county: 'Co. Down',
          postcode: 'BT30 6LP',
        },
        type: 'Estate Agent',
        network: 'Quinn Property Sales & Letting Specialists',
        chatEnabled: true,
        url: 'http://www.quinnestateagents.com',
      },
    ],
    location: 'gcevn1hm8t',
    sector: ['Residential'],
  },
  {
    id: 'MOQ754662',
    propertyUrl: '/property-for-sale/dunteige-road-omagh-bt78-5pb/property/MOQ754662/',
    address: {
      buildingName: 'Site @',
      line1: 'Dunteige Road',
      town: 'Omagh',
      county: 'Tyrone',
      postcode: 'BT785PB',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/MOQ754662/photo/image/de37a475-bcb0-443f-9677-f55e1b9b7fbd/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/MOQ754662/photo/image/de37a475-bcb0-443f-9677-f55e1b9b7fbd/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/MOQ754662/photo/image/de37a475-bcb0-443f-9677-f55e1b9b7fbd/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/MOQ754662/photo/image/de37a475-bcb0-443f-9677-f55e1b9b7fbd/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 3,
    price: 30000,
    currency: 'GBP',
    priceText: 'Offers Around',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Residential Land (with no PP)',
    isNew: false,
    enhanced: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 1406,
        logo: {
          name: 'Mortgage and Property Plus',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/1406/logo/image/b7087c1f4f89e63af8d46f3b20271153/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/1406/logo/image/b7087c1f4f89e63af8d46f3b20271153/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/1406/logo/image/b7087c1f4f89e63af8d46f3b20271153/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/1406/logo/image/b7087c1f4f89e63af8d46f3b20271153/600x500.png',
            },
          ],
        },
        name: 'Mortgage and Property Plus',
        phoneNumber: '028 8224 6538',
        featured: true,
        companyInfo:
          'Mortgage and Property Plus is an estate agent in Omagh. William Sayers established Mortgage and Property Plus in 2002 after working previously in Financial Services, specialising particularly in mortgages.\r\n\r\nThe agency offers a wide variety of services in the following areas:\r\n\r\n-\tResidential sales\r\n-\tResidential lettings\r\n-\tCommercial sales\r\n-\tCommercial lettings\r\n-\tLand and site sales\r\n',
        address: {
          line1: '11 Campsie Road',
          town: 'Omagh',
          county: 'Co. Tyrone',
          postcode: 'BT79 0AE',
        },
        type: 'Estate Agent',
        network: 'Mortgage and Property Plus',
        chatEnabled: true,
        url: 'http://www.mortgageandpropertyplus.com',
      },
    ],
    location: 'gcdybk6325',
    sector: ['Residential'],
  },
  {
    id: 'IPE11632',
    propertyUrl: '/property-for-sale/site-comber-bt23-5ws/property/IPE11632/',
    address: {
      line1: 'Site',
      line2: 'Mill Village',
      town: 'Comber',
      county: 'Down',
      postcode: 'BT235WS',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/IPE11632/photo/image/eea90382-f3b8-41d8-a6fe-d84697054b33/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/IPE11632/photo/image/eea90382-f3b8-41d8-a6fe-d84697054b33/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/IPE11632/photo/image/eea90382-f3b8-41d8-a6fe-d84697054b33/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/IPE11632/photo/image/eea90382-f3b8-41d8-a6fe-d84697054b33/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 7,
    price: 20000,
    currency: 'GBP',
    priceText: 'Offers Over',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Land',
    isNew: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 7295,
        logo: {
          name: 'Independent Property Estates Ltd',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/7295/logo/image/a3e1a5ac-0d70-4d64-b659-945074462556/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/7295/logo/image/a3e1a5ac-0d70-4d64-b659-945074462556/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/7295/logo/image/a3e1a5ac-0d70-4d64-b659-945074462556/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/7295/logo/image/a3e1a5ac-0d70-4d64-b659-945074462556/600x500.png',
            },
          ],
        },
        name: 'Independent Property Estates Ltd',
        phoneNumber: '028 9145 0000',
        featured: false,
        companyInfo:
          'Independent Property Estates is part of The Independent Group of Companies and was established in 2008 by Michael Rushe, principal of this group. \r\n\r\nIndependent Property Estates now provides an innovative, contemporary Estate Agency Service working alongside Independent Mortgage & Investment Advisors and several other divisions of The Independent Group of Companies. \r\n\r\nIndependent Property Estates offer a full, comprehensive professional property service providing dynamic solutions for Sellers, Buyers, Landlords and Tenants of Residential and Commercial Property in North Down and across Northern Ireland.\r\n',
        address: {
          line1: '11 Hamilton Road',
          town: 'Bangor',
          county: 'Co. Down',
          postcode: 'BT20 4JP',
        },
        type: 'Estate Agent',
        network: 'Independent Property Estates Ltd',
        chatEnabled: true,
        url: 'http://www.ipestates.co.uk',
      },
    ],
    location: 'gceym445y1',
    locationDescription: 'Within the Mill Village Development',
    sector: ['Residential'],
  },
  {
    id: 'TRLIS26145798',
    propertyUrl: '/property-for-sale/76-lower-quilly-road-dromore-bt25-1lj/property/TRLIS26145798/',
    address: {
      buildingName: 'Lands At',
      line1: 'Land @ 76 Lower Quilly Road',
      town: 'Dromore',
      postcode: 'BT251LJ',
    },
    leadImage: {
      sizes: [
        {
          size: '320w',
          width: '320',
          height: '231',
          url: 'https://media.propertynews.com/property/TRLIS26145798/photo/image/dda1dae8-cde4-4ddf-9ffd-6c4ee164aaa5/320x231.webp',
        },
        {
          size: '640w',
          width: '600',
          height: '500',
          url: 'https://media.propertynews.com/property/TRLIS26145798/photo/image/dda1dae8-cde4-4ddf-9ffd-6c4ee164aaa5/600x500.webp',
        },
        {
          size: '1024w',
          width: '1000',
          height: '800',
          url: 'https://media.propertynews.com/property/TRLIS26145798/photo/image/dda1dae8-cde4-4ddf-9ffd-6c4ee164aaa5/1000x800.webp',
        },
        {
          size: '1600w',
          width: '1600',
          height: '1067',
          url: 'https://media.propertynews.com/property/TRLIS26145798/photo/image/dda1dae8-cde4-4ddf-9ffd-6c4ee164aaa5/1600x1067.webp',
        },
      ],
    },
    enhancedImages: [],
    imageCount: 3,
    price: 30000,
    currency: 'GBP',
    priceText: 'From',
    status: 'For Sale',
    bedrooms: '0',
    bathrooms: 0,
    receptionRooms: 0,
    propertyType: 'Land (Single Dwelling)',
    propertyTypeLabel: 'Land (Single Dwelling)',
    isNew: false,
    enhanced: false,
    epcRatingCurrent: '0',
    epcRatingPotential: '0',
    agents: [
      {
        id: 7883,
        logo: {
          name: 'Templeton Robinson (Lisburn)',
          sizes: [
            {
              size: '80w',
              width: '94',
              height: '80',
              url: 'https://media.propertynews.com/agent/7883/logo/image/3f8e8bb571cc086ca44e9605ad23ffde/94x80.png',
            },
            {
              size: '160w',
              width: '160',
              height: '160',
              url: 'https://media.propertynews.com/agent/7883/logo/image/3f8e8bb571cc086ca44e9605ad23ffde/160x160.png',
            },
            {
              size: '320w',
              width: '320',
              height: '231',
              url: 'https://media.propertynews.com/agent/7883/logo/image/3f8e8bb571cc086ca44e9605ad23ffde/320x231.png',
            },
            {
              size: '600w',
              width: '600',
              height: '500',
              url: 'https://media.propertynews.com/agent/7883/logo/image/3f8e8bb571cc086ca44e9605ad23ffde/600x500.png',
            },
          ],
        },
        name: 'Templeton Robinson (Lisburn)',
        phoneNumber: '028 9266 1700',
        featured: false,
        companyInfo:
          'Established back in 1994, Templeton Robinson is the Leading Residential Estate agency practice in the province. They pride themselves on being the agent of choice for homes of all sizes as Northern Ireland’s ‘local estate agent’.\r\n\r\nTempleton Robinson has four branches: Lisburn Road, North Down, Ballyhackamore and Lisburn. The agency specialises in resales, rentals, development of agricultural land and major new-build housing schemes, both corporate and private. \r\n\r\nTempleton Robinson combines cutting-edge technology and personal contact to achieve success. The team are vastly experienced and friendly, and the agency prides itself on providing a uniquely personal experience. Thousands of clients each year choose Templeton Robinson as their “Agent for Life” in what has become a fragmented and cluttered marketplace. ',
        address: {
          line1: '17 Market Place',
          town: 'Lisburn',
          county: 'Co. Antrim',
          postcode: 'BT28 1AN',
        },
        type: 'Estate Agent',
        network: 'Templeton Robinson',
        chatEnabled: true,
        url: 'http://www.templetonrobinson.com',
      },
    ],
    location: 'gcetdbx836',
    locationDescription:
      'From the A1 Duel Carriageway take the Lower Quilly Road for approximately 2 miles and Greenan Manor is on the right hand side.',
    sector: ['Residential'],
  },
];
